version: 1.0
provider:
  name: openfaas
  gateway: 127.0.0.1:8080
functions:
  video-transcode:
    lang: python3-http-debian
    handler: ./video-transcode
    image: ghcr.io/rei-smz/video-transcode:latest
    build-args:
      ADDITIONAL_PACKAGE: ffmpeg
    # build_options:
    #   - name: transcode
    #     packages:
    #       - ffmpeg
    environment:
      MINIO_ENDPOINT: "s3endpoint"
      BUCKET_NAME: "openwhisk-bkt"
      exec_timeout: "30m"
      read_timeout: "30m"
      write_timeout: "30m"
    secrets:
      - minio-access-key
      - minio-secret-key
    requests:
      cpu: 11000m
    limits:
      cpu: 16000m
      
