version: 1.0
provider:
  name: openfaas
  gateway: http://128.110.217.187:31112
functions:
  video-transcode:
    lang: python3-http-debian
    handler: ./video-transcode
    image: lzlzq/video-transcode:latest
    build-args:
      ADDITIONAL_PACKAGE: ffmpeg
    # build_options:
    #   - name: transcode
    #     packages:
    #       - ffmpeg
    environment:
      MINIO_ENDPOINT: "s3.128.110.217.187.nip.io:31999"
      BUCKET_NAME: "faas-bkt"
      exec_timeout: "30m"
      read_timeout: "30m"
      write_timeout: "30m"
    secrets:
      - minio-access-key
      - minio-secret-key
    requests:
      cpu: 11000m
    limits:
      cpu: 16000m
      