version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  video-transcode:
    lang: python3-http-debian
    handler: ./video-transcode
    image: your_username/video-transcode:latest
    build-args:
      ADDITIONAL_PACKAGE: "ffmpeg"
    environment:
      MINIO_ENDPOINT: "your_minio_s3_addr"
      BUCKET_NAME: "your_bkt_name"
    secrets:
      - minio-access-key
      - minio-secret-key

